$default = "install"

function update {
   Remove-Item .\Dotfiles.psm1 -ErrorAction Continue
  (Write-Output "<# Autogenerated by update.ps1. Do not edit manually #>") > .\Dotfiles.psm1
    Get-ChildItem .\modules\*.ps1 | ForEach-Object { Get-Content $_ >> .\Dotfiles.psm1 }
}

function requirements {
  PowerShellGet\Install-Module posh-git -Scope CurrentUser -Force  
}
function install {
  update
  $moduleDir = $(Join-Path $HOME "Documents" "Powershell" "Modules" "dotfiles")

  "Dotfiles.psd1", "Dotfiles.psm1" | ForEach-Object { Copy-Item $_ $moduleDir }
}