$default = "update"

function update {
    Remove-Item .\Dotfiles.psm1 -ErrorAction Continue

(Write-Output "<# Autogenerated by update.ps1. Do not edit manually #>") > .\Dotfiles.psm1
    Get-ChildItem .\modules\*.ps1 | ForEach-Object { Get-Content $_ >> .\Dotfiles.psm1 }
}